# NOTE: Version 3.9 requires at least Docker Compose version 2 and Docker Engine version 20.10.13!
# To boot the app run the following:
# docker compose up --build

version: "3.9"

services:
  threader:
    build: 
      context: ./
      target: threader-release
      args:
        - BUILD_TYPE=release # Configurate your build type (-dev | -release)
    env_file:
      - .env # Ensure your variables have been set before running 'Docker-Compose'
    environment:
      - THREADS_USERNAME=${THREADS_USERNAME}
      - THREADS_PASSWORD=${THREADS_PASSWORD}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - ./:/app
      - ./docker-compose.yml:/app/docker-compose.yml:ro
      - ./Dockerfile:/app/Dockerfile:ro
    command: python main.py
